INSERT INTO Books (Title, Author, Description, FilePath)
VALUES 
('To Kill a Mockingbird', 'Harper Lee', 'A novel about the serious issues of rape and racial inequality.', 'path/to/to_kill_a_mockingbird.pdf'),
('1984', 'George Orwell', 'A dystopian novel set in a totalitarian society under constant surveillance.', 'path/to/1984.pdf'),
('Pride and Prejudice', 'Jane Austen', 'A romantic novel that charts the emotional development of the protagonist.', 'path/to/pride_and_prejudice.pdf'),
('The Great Gatsby', 'F. Scott Fitzgerald', 'A story about the young and mysterious millionaire Jay Gatsby and his quixotic passion for the beautiful Daisy Buchanan.', 'path/to/the_great_gatsby.pdf'),
('Moby Dick', 'Herman Melville', 'The narrative of the adventures of the wandering sailor Ishmael and his voyage on the whaleship Pequod.', 'path/to/moby_dick.pdf'),
('War and Peace', 'Leo Tolstoy', 'A historical novel that tells the story of five families and their struggles during the Napoleonic Wars.', 'path/to/war_and_peace.pdf'),
('The Catcher in the Rye', 'J.D. Salinger', 'A story about the experiences of a young boy named Holden Caulfield.', 'path/to/the_catcher_in_the_rye.pdf'),
('The Hobbit', 'J.R.R. Tolkien', 'A fantasy novel and childrens book by J.R.R. Tolkien.', 'path/to/the_hobbit.pdf'),
('Fahrenheit 451', 'Ray Bradbury', 'A dystopian novel that presents a future American society where books are outlawed and "firemen" burn any that are found.', 'path/to/fahrenheit_451.pdf'),
('Crime and Punishment', 'Fyodor Dostoevsky', 'A novel that focuses on the mental anguish and moral dilemmas of Raskolnikov, an impoverished ex-student.', 'path/to/crime_and_punishment.pdf'),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'A passionate philosophical novel set in 19th-century Russia, that enters deeply into the ethical debates of God, free will, and morality.', 'path/to/the_brothers_karamazov.pdf'),
('Brave New World', 'Aldous Huxley', 'A dystopian novel set in a futuristic World State, whose citizens are environmentally engineered into an intelligence-based social hierarchy.', 'path/to/brave_new_world.pdf'),
('The Odyssey', 'Homer', 'An ancient Greek epic poem attributed to Homer, recounting the adventures of Odysseus during his return home from the Trojan War.', 'path/to/the_odyssey.pdf'),
('Jane Eyre', 'Charlotte Brontë', 'A novel that follows the emotions and experiences of its title character, including her growth to adulthood and her love for Mr. Rochester.', 'path/to/jane_eyre.pdf'),
('Wuthering Heights', 'Emily Brontë', 'A story of love and revenge set on the bleak Yorkshire moors.', 'path/to/wuthering_heights.pdf'),
('The Divine Comedy', 'Dante Alighieri', 'An epic poem describing Dantes journey through Hell, Purgatory, and Paradise.', 'path/to/the_divine_comedy.pdf'),
('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'A multi-generational story that follows the Buendia family and their mythical town of Macondo.', 'path/to/one_hundred_years_of_solitude.pdf'),
('The Picture of Dorian Gray', 'Oscar Wilde', 'A philosophical novel about a young man whose portrait ages while he remains youthful.', 'path/to/the_picture_of_dorian_gray.pdf'),
('Catch-22', 'Joseph Heller', 'A satirical novel set during World War II, focusing on the absurdities of war and military life.', 'path/to/catch_22.pdf'),
('Anna Karenina', 'Leo Tolstoy', 'A complex novel in eight parts, dealing with themes of betrayal, faith, family, marriage, Imperial Russian society, desire, and rural vs. city life.', 'path/to/anna_karenina.pdf'),
('The Count of Monte Cristo', 'Alexandre Dumas', 'A historical novel set in the early 19th century about a man who is wrongfully imprisoned, escapes, and seeks revenge.', 'path/to/the_count_of_monte_cristo.pdf'),
('Les Misérables', 'Victor Hugo', 'A historical novel set in the early 19th century about the struggles and redemption of ex-convict Jean Valjean.', 'path/to/les_miserables.pdf'),
('Don Quixote', 'Miguel de Cervantes', 'A Spanish novel about a man who becomes a knight-errant in search of adventure.', 'path/to/don_quixote.pdf'),
('The Catcher in the Rye', 'J.D. Salinger', 'A story about the experiences of a young boy named Holden Caulfield.', 'path/to/the_catcher_in_the_rye.pdf'),
('The Metamorphosis', 'Franz Kafka', 'A novella about a man who transforms into a giant insect.', 'path/to/the_metamorphosis.pdf'),
('Heart of Darkness', 'Joseph Conrad', 'A novella about a voyage up the Congo River into the Congo Free State in the heart of Africa.', 'path/to/heart_of_darkness.pdf'),
('Ulysses', 'James Joyce', 'A modernist novel that parallels the structure of Homers Odyssey.', 'path/to/ulysses.pdf'),
('Frankenstein', 'Mary Shelley', 'A novel about a young scientist who creates a grotesque creature in an unorthodox scientific experiment.', 'path/to/frankenstein.pdf'),
('Dracula', 'Bram Stoker', 'A Gothic horror novel about Count Draculas attempt to move from Transylvania to England.', 'path/to/dracula.pdf'),
('The Canterbury Tales', 'Geoffrey Chaucer', 'A collection of 24 stories presented as part of a storytelling contest by a group of pilgrims.', 'path/to/the_canterbury_tales.pdf'),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'A historical novel set in 17th-century Puritan Massachusetts.', 'path/to/the_scarlet_letter.pdf'),
('Gullivers Travels', 'Jonathan Swift', 'A satirical novel about the travels of Lemuel Gulliver.', 'path/to/gullivers_travels.pdf'),
('Treasure Island', 'Robert Louis Stevenson', 'An adventure novel about buccaneers and buried gold.', 'path/to/treasure_island.pdf'),
('The Three Musketeers', 'Alexandre Dumas', 'A historical novel set in the 17th century about a young man who leaves home to become a musketeer of the guard.', 'path/to/the_three_musketeers.pdf'),
('The Adventures of Huckleberry Finn', 'Mark Twain', 'A novel about a boys adventures along the Mississippi River.', 'path/to/the_adventures_of_huckleberry_finn.pdf'),
('The Strange Case of Dr Jekyll and Mr Hyde', 'Robert Louis Stevenson', 'A novella about a London lawyer who investigates the strange occurrences between his old friend Dr. Henry Jekyll and the evil Edward Hyde.', 'path/to/the_strange_case_of_dr_jekyll_and_mr_hyde.pdf'),
('Moby-Dick', 'Herman Melville', 'The narrative of the adventures of the wandering sailor Ishmael and his voyage on the whaleship Pequod.', 'path/to/moby_dick.pdf'),
('The Iliad', 'Homer', 'An ancient Greek epic poem attributed to Homer, detailing the events of the Trojan War.', 'path/to/the_iliad.pdf'),
('The Grapes of Wrath', 'John Steinbeck', 'A novel about the hardships of the Great Depression and the Dust Bowl migration.', 'path/to/the_grapes_of_wrath.pdf'),
('The Old Man and the Sea', 'Ernest Hemingway', 'A novella about an aging Cuban fisherman who struggles with a giant marlin far out in the Gulf Stream.', 'path/to/the_old_man_and_the_sea.pdf');
